# Generated by Django 4.1 on 2022-08-22 20:05

from django.db import migrations, models
import version_1.models


class Migration(migrations.Migration):

    dependencies = [
        ('version_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaraunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('menu_as_link', models.CharField(blank=True, max_length=255, null=True)),
                ('menu_as_file', models.FileField(blank=True, null=True, upload_to=version_1.models.save_restaurant_menu)),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
